version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: employeedb
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: EmployeeDbContext
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - employee-network

  api:
    build:
      context: .
      dockerfile: EmployeeManagement.Api/Dockerfile
    container_name: employee-api
    depends_on:
      - postgres
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - employee-network

volumes:
  pgdata:

networks:
  employee-network:
